"""Auto-generated Medical Taxonomy from training data.

This file is AUTO-GENERATED by auto_extract_taxonomy.py
DO NOT EDIT MANUALLY - changes will be overwritten!

To regenerate: python -m rag_system.auto_extract_taxonomy
"""

import unicodedata
from typing import List, Dict, Optional, Tuple


def remove_diacritics(text: str) -> str:
    """Remove Vietnamese diacritics from text."""
    nfd = unicodedata.normalize('NFD', text)
    without_diacritics = ''.join(char for char in nfd if unicodedata.category(char) != 'Mn')
    return without_diacritics


# ============================================================================
# AUTO-EXTRACTED MEDICAL CONDITIONS
# ============================================================================

MEDICAL_CONDITIONS = {
    "ung_thu": {
        "names": ['ung thư', 'ung thu', 'cancer', 'khối u', 'hóa trị', 'xạ trị', 'tế bào ung thư'],
        "keywords": ['ung thư', 'ung thu', 'cancer', 'khối u', 'hóa trị', 'xạ trị', 'tế bào ung thư'],
        "products": ['The Fucoidan', 'The Fucoidan xK (Phiên bản nâng cấp)', 'β-Glucan Ball']
    },
    "mien_dich": {
        "names": ['miễn dịch', 'mien dich', 'đề kháng', 'de khang', 'hệ miễn dịch'],
        "keywords": ['miễn dịch', 'mien dich', 'đề kháng', 'de khang', 'hệ miễn dịch'],
        "products": ['The Fucoidan', 'The Fucoidan xK (Phiên bản nâng cấp)', 'β-Glucan Ball', 'The Reishi']
    },
    "bo_than": {
        "names": ['bổ thận', 'bo than', 'thận', 'than', 'thận yếu'],
        "keywords": ['bổ thận', 'bo than', 'thận', 'than', 'thận yếu'],
        "products": ["Kidney & Men's", 'Power HLP', 'The Fucoidan', 'The Fucoidan xK (Phiên bản nâng cấp)', 'The Reishi']  # Kidney & Men's FIRST - most specific for kidney support
    },
    "tieu_duong": {
        "names": ['tiểu đường', 'tieu duong', 'đái tháo đường', 'dai thao duong', 'diabetes'],
        "keywords": ['tiểu đường', 'tieu duong', 'đái tháo đường', 'dai thao duong', 'diabetes'],
        "products": ['The Fucoidan']
    },
    "tim_mach": {
        "names": ['tim mạch', 'tim', 'mạch máu', 'nhồi máu cơ tim', 'xơ vữa động mạch'],
        "keywords": ['tim mạch', 'tim', 'mạch máu', 'nhồi máu cơ tim', 'xơ vữa động mạch'],
        "products": ['The Fucoidan', 'The Fucoidan xK (Phiên bản nâng cấp)', 'Power HLP']
    },
    "ngu": {
        "names": ['ngủ', 'ngu', 'giấc ngủ', 'mất ngủ', 'mat ngu'],
        "keywords": ['ngủ', 'ngu', 'giấc ngủ', 'mất ngủ', 'mat ngu'],
        "products": ['The Fucoidan', 'The Fucoidan xK (Phiên bản nâng cấp)', 'β-Glucan Ball', "Kidney & Men's", 'Power HLP', 'The Reishi']
    },
    "gan": {
        "names": ['gan', 'giải độc gan', 'gan nhiễm mỡ', 'bệnh gan'],
        "keywords": ['gan', 'giải độc gan', 'gan nhiễm mỡ', 'bệnh gan'],
        "products": ['The Fucoidan xK (Phiên bản nâng cấp)', 'The Reishi']
    },
    "sinh_ly_nam": {
        "names": ['sinh lý nam', 'sinh ly nam', 'tráng dương', 'testosterone', 'sinh lực nam'],
        "keywords": ['sinh lý nam', 'sinh ly nam', 'tráng dương', 'testosterone', 'sinh lực nam'],
        "products": ["Kidney & Men's"]
    },
    "stress": {
        "names": ['stress', 'căng thẳng', 'cang thang', 'lo âu'],
        "keywords": ['stress', 'căng thẳng', 'cang thang', 'lo âu'],
        "products": ["Kidney & Men's", 'The Reishi']
    },
    "dau": {
        "names": ['đau', 'dau', 'giảm đau', 'nhức'],
        "keywords": ['đau', 'dau', 'giảm đau', 'nhức'],
        "products": ["Kidney & Men's", 'Power HLP']
    },
    "dot_quy": {
        "names": ['đột quỵ', 'dot quy', 'tai biến mạch máu não', 'tai bien'],
        "keywords": ['đột quỵ', 'dot quy', 'tai biến mạch máu não', 'tai bien'],
        "products": ['Power HLP']
    },
    "mau_dong": {
        "names": ['máu đông', 'mau dong', 'cục máu đông', 'huyết khối'],
        "keywords": ['máu đông', 'mau dong', 'cục máu đông', 'huyết khối'],
        "products": ['Power HLP']
    },
    "cholesterol": {
        "names": ['cholesterol', 'mỡ máu', 'mo mau', 'lipid'],
        "keywords": ['cholesterol', 'mỡ máu', 'mo mau', 'lipid'],
        "products": ['Power HLP', 'The Reishi']
    },
    "cao_huyet_ap": {
        "names": ['cao huyết áp', 'cao huyet ap', 'huyết áp cao', 'huyết áp'],
        "keywords": ['cao huyết áp', 'cao huyet ap', 'huyết áp cao', 'huyết áp'],
        "products": ['The Reishi']
    },
}

# ============================================================================
# AUTO-EXTRACTED PRODUCT-CONDITION MAPPINGS
# ============================================================================

PRODUCT_CONDITIONS = {
    "The Fucoidan": {
        "primary_conditions": ['ung_thu', 'mien_dich', 'bo_than', 'tieu_duong', 'tim_mach', 'ngu'],
        "keywords": ['ung thư', 'miễn dịch', 'thận', 'tiểu đường', 'tim mạch'],  # Top 5 keywords
        "description": """Chứa 100% tinh chất Fucoidan chiết xuất từ Tảo nâu Okinawa Mozuku Nhật Bản với hàm lượng Fucoidan cao 200mg/viên (1200mg/liều dùng). Sản phẩm đã có mặt trên thị trường 10 năm và có giá thành cạnh tran..."""
    },
    "The Fucoidan xK (Phiên bản nâng cấp)": {
        "primary_conditions": ['ung_thu', 'mien_dich', 'bo_than', 'gan', 'tim_mach', 'ngu'],
        "keywords": ['ung thư', 'miễn dịch', 'thận', 'gan', 'mạch máu'],  # Top 5 keywords
        "description": """Công thức tối ưu cho hệ miễn dịch, kết hợp 3 thành phần quý hiếm: Tảo Nâu Mozuku (hàm lượng Fucoidan 200mg/viên), Đông Trùng Hạ Thảo (20mg/viên) và Nấm Agaricus (10mg/viên). Hàm lượng tinh chất Fucoid..."""
    },
    "β-Glucan Ball": {
        "primary_conditions": ['ung_thu', 'mien_dich', 'ngu'],
        "keywords": ['ung thư', 'đề kháng', 'ngủ'],  # Top 5 keywords
        "description": """Chiết xuất từ 9 loại nấm quý Nhật Bản (Đông Trùng Hạ Thảo, Linh Chi, Agaricus, Nấm Thông, Chaga, Linh chi Rokkaku, Maitake, Phellinus, Nấm Súp Ld). Hàm lượng Beta Glucan Ball cao 169mg/liều dùng. Dạng..."""
    },
    "Kidney & Men's": {
        "primary_conditions": ['bo_than', 'sinh_ly_nam', 'stress', 'ngu', 'dau'],
        "keywords": ['bổ thận', 'sinh lý nam', 'căng thẳng', 'ngủ', 'dau'],  # Top 5 keywords
        "description": """Công thức kết hợp đồng thời 8 dược liệu quý hiếm Nhật Bản (Sâm Cau, Bạch Quả, Phá Cố Chỉ, Nhân Sâm, Nhung Hươu, Nhục Thung Dung, Sơn Thù Du, Rễ Củ Mài). Đây là sản phẩm bổ thận và sinh lý nam cao cấp ..."""
    },
    "Power HLP": {
        "primary_conditions": ['bo_than', 'dot_quy', 'mau_dong', 'cholesterol', 'tim_mach', 'ngu', 'dau'],
        "keywords": ['thận', 'đột quỵ', 'máu đông', 'cholesterol', 'tim'],  # Top 5 keywords
        "description": """Bí quyết phòng ngừa và hồi phục đột quỵ từ Nhật Bản. Nguồn nguyên liệu trùn đất được Waki trực tiếp nuôi và thu hoạch tại Zara, Nhật Bản theo quy trình đạt chuẩn GMP. Quy trình sản xuất trùn đất được ..."""
    },
    "The Reishi": {
        "primary_conditions": ['mien_dich', 'bo_than', 'cholesterol', 'cao_huyet_ap', 'gan', 'stress', 'ngu'],
        "keywords": ['miễn dịch', 'thận', 'cholesterol', 'huyết áp', 'gan'],  # Top 5 keywords
        "description": """Công thức kết hợp 2IN1 Xích Linh Chi (120mg/viên) và Nấm Agaricus (50mg/viên) từ Nhật Bản. Hàm lượng nấm linh chi cao 480mg/liều dùng. 
 Hỗ trợ hệ miễn dịch, tăng cường sức khỏe cơ thể, giải độc gan, ..."""
    },
}


def detect_medical_condition(query: str) -> Optional[Tuple[str, Dict]]:
    """Detect medical condition from user query."""
    query_lower = query.lower()
    query_no_diacritics = remove_diacritics(query_lower)
    
    best_match = None
    best_score = 0
    
    for condition_id, condition_info in MEDICAL_CONDITIONS.items():
        for name in condition_info["names"]:
            name_lower = name.lower()
            name_no_diacritics = remove_diacritics(name_lower)
            
            if name_lower in query_lower:
                return (condition_id, condition_info)
            
            if name_no_diacritics in query_no_diacritics:
                return (condition_id, condition_info)
        
        for keyword in condition_info["keywords"]:
            keyword_lower = keyword.lower()
            keyword_no_diacritics = remove_diacritics(keyword_lower)
            
            if keyword_lower in query_lower or keyword_no_diacritics in query_no_diacritics:
                score = len(keyword)
                if score > best_score:
                    best_score = score
                    best_match = (condition_id, condition_info)
    
    return best_match


def find_products_for_condition(condition_id: str) -> List[str]:
    """Find all products that treat a specific medical condition."""
    condition_info = MEDICAL_CONDITIONS.get(condition_id)
    if condition_info:
        return condition_info.get("products", [])
    return []


def detect_product_mention(query: str) -> Optional[str]:
    """Detect if user is asking about a specific product by name.
    
    Returns:
        Product name if detected, None otherwise
    """
    query_lower = query.lower()
    query_no_diacritics = remove_diacritics(query_lower)
    
    # Check all product names
    for product_name in PRODUCT_CONDITIONS.keys():
        product_lower = product_name.lower()
        product_no_diacritics = remove_diacritics(product_lower)
        
        # Exact match or contains
        if product_lower in query_lower or product_no_diacritics in query_no_diacritics:
            return product_name
        
        # Check for partial matches (e.g., "fucoidan" should match "The Fucoidan")
        product_words = product_name.lower().split()
        for word in product_words:
            if len(word) > 4:  # Only check meaningful words
                word_no_diacritics = remove_diacritics(word)
                if word in query_lower or word_no_diacritics in query_no_diacritics:
                    return product_name
    
    return None


def detect_condition_and_products(query: str) -> Optional[Dict]:
    """Complete pipeline: Detect product mention OR condition and find matching products.
    
    Priority:
    1. Product name mentioned → Use that product
    2. Condition detected → Find products for that condition
    """
    # 🔍 STEP 1: Check if user is asking about a specific product
    product_name = detect_product_mention(query)
    if product_name:
        print(f"🏷️  Product mentioned directly: {product_name}")
        return {
            "condition_id": None,
            "condition_name": None,
            "products": [product_name],
            "query_type": "product_search"
        }
    
    # 🔍 STEP 2: No product mentioned → Try condition detection
    condition_match = detect_medical_condition(query)
    
    if not condition_match:
        return None
    
    condition_id, condition_info = condition_match
    products = condition_info.get("products", [])
    
    if not products:
        return None
    
    return {
        "condition_id": condition_id,
        "condition_name": condition_info["names"][0],
        "products": products,
        "query_type": "condition_search"
    }
